#!/bin/sh

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

export NODE_ENV="test"

npm i

echo "===> Running linter..."

./node_modules/semistandard/bin/cmd.js

echo "===> Running tests..."

./node_modules/.bin/lab -l -v test/boot.js test/index.js
